# Generated by Django 4.0 on 2023-02-05 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_typedebien_alter_book_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=60)),
                ('prénom', models.CharField(max_length=60)),
                ('mot_de_passe', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Maison',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('superficie', models.CharField(max_length=60)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=4)),
                ('quartier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.genre')),
            ],
        ),
        migrations.CreateModel(
            name='Appartement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('superficie', models.CharField(max_length=60)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=4)),
                ('quartier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.genre')),
            ],
        ),
    ]
