# Generated by Django 4.0 on 2023-02-05 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_commune_alter_maison_quartier'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Commune',
            new_name='Quartier',
        ),
    ]
