# Generated by Django 4.0 on 2023-02-05 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_rename_commune_quartier'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Genre',
            new_name='Action',
        ),
        migrations.AlterField(
            model_name='appartement',
            name='quartier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.quartier'),
        ),
    ]
