# Generated by Django 4.0 on 2023-02-05 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0006_rename_genre_action_alter_appartement_quartier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Magazin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('superficie', models.CharField(max_length=60)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=4)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.action')),
                ('quartier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.quartier')),
            ],
        ),
        migrations.CreateModel(
            name='Terrain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.action')),
                ('quartier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.quartier')),
            ],
        ),
        migrations.AddField(
            model_name='appartement',
            name='genre',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='search.action'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maison',
            name='genre',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='search.action'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
