# Generated by Django 4.0 on 2023-02-05 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0007_magazin_terrain_appartement_genre_maison_genre_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appartement',
            old_name='genre',
            new_name='action',
        ),
        migrations.RenameField(
            model_name='magazin',
            old_name='genre',
            new_name='action',
        ),
        migrations.RenameField(
            model_name='maison',
            old_name='genre',
            new_name='action',
        ),
        migrations.RenameField(
            model_name='terrain',
            old_name='genre',
            new_name='action',
        ),
    ]
