# Generated by Django 4.0 on 2023-02-11 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0008_rename_genre_appartement_action_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='terrain',
            old_name='name',
            new_name='superficie',
        ),
        migrations.RemoveField(
            model_name='terrain',
            name='price',
        ),
    ]
