# Generated by Django 4.1.5 on 2023-02-17 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propriété', '0002_profile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
